using System;
using Fantasy.SourceGenerator.Common;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Linq;
using System.Text;
#pragma warning disable CS8602 // Dereference of a possibly null reference.

namespace Fantasy.SourceGenerator.Generators
{
    /// <summary>
    /// Entity System 注册代码生成器
    /// 自动生成 EntityComponent 所需的 System 注册代码，替代运行时反射
    /// </summary>
    [Generator]
    public partial class EntitySystemGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // 查找所有实现了 IEntitySystem 相关接口的类
            var systemTypes = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => IsSystemClass(node),
                    transform: static (ctx, _) => GetSystemTypeInfo(ctx))
                .Where(static info => info != null)
                .Collect();
            // 组合编译信息和找到的类型
            var compilationAndTypes = context.CompilationProvider.Combine(systemTypes);
            // 注册源代码输出
            context.RegisterSourceOutput(compilationAndTypes, static (spc, source) =>
            {
                if (CompilationHelper.IsSourceGeneratorDisabled(source.Left))
                {
                    return;
                }
                
                if (!CompilationHelper.HasFantasyDefine(source.Left))
                {
                    return;
                }
                
                if (source.Left.GetTypeByMetadataName("Fantasy.Assembly.IEntitySystemRegistrar") == null)
                {
                    return;
                }

                GenerateRegistrationCode(spc, source.Left, source.Right!);
            });
        }
        
        private static EntitySystemTypeInfo? GetSystemTypeInfo(GeneratorSyntaxContext context)
        {
            var classDecl = (ClassDeclarationSyntax)context.Node;

            if (context.SemanticModel.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol symbol || !symbol.IsInstantiable())
            {
                return null;
            }
            
            var baseType = symbol.BaseType;

            if (!baseType.IsGenericType)
            {
                return null;
            }
       
            return baseType.Name switch
            {
                "AwakeSystem" => EntitySystemTypeInfo.Create(EntitySystemType.AwakeSystem, symbol),
                "UpdateSystem" => EntitySystemTypeInfo.Create(EntitySystemType.UpdateSystem, symbol),
                "DestroySystem" => EntitySystemTypeInfo.Create(EntitySystemType.DestroySystem, symbol),
                "DeserializeSystem" => EntitySystemTypeInfo.Create(EntitySystemType.DeserializeSystem, symbol),
                "LateUpdateSystem" => EntitySystemTypeInfo.Create(EntitySystemType.LateUpdateSystem, symbol),
                _ => null
            };
        }
        
        private static void GenerateRegistrationCode(
            SourceProductionContext context,
            Compilation compilation,
            IEnumerable<EntitySystemTypeInfo> systemTypes)
        {
            var entitySystemTypeInfos = systemTypes.ToList();
            // 获取当前程序集名称（仅用于注释）
            var markerClassName = compilation.GetAssemblyName("EntitySystemRegistrar", out var assemblyName, out _);
            // 生成代码文件
            var builder = new SourceCodeBuilder();
            // 添加文件头
            builder.AppendLine(GeneratorConstants.AutoGeneratedHeader);
            // 添加 using
            builder.AddUsings(
                "System",
                "System.Collections.Generic",
                "Fantasy.Assembly",
                "Fantasy.Entitas",
                "Fantasy.Entitas.Interface"
            );
            builder.AppendLine();
            // 开始命名空间（固定使用 Fantasy.Generated）
            builder.BeginNamespace("Fantasy.Generated");
            // 开始类定义（实现 IEntitySystemRegistrar 接口）
            builder.AddXmlComment($"Auto-generated Entity System registration class for {assemblyName}");
            builder.BeginClass(markerClassName, "internal sealed", "global::Fantasy.Assembly.IEntitySystemRegistrar");
            // 生成Code
            GenerateCode(builder, entitySystemTypeInfos);
            // 结束类和命名空间
            builder.EndClass();
            builder.EndNamespace();
            // 输出源代码
            context.AddSource($"{markerClassName}.g.cs", builder.ToString());
        }

        private static void GenerateCode(SourceCodeBuilder builder, List<EntitySystemTypeInfo> entitySystemTypeInfos)
        {
            var awake = new List<EntitySystemTypeInfo>();
            var update = new List<EntitySystemTypeInfo>();
            var destroy = new List<EntitySystemTypeInfo>();
            var deserialize = new List<EntitySystemTypeInfo>();
            var lateUpdate = new List<EntitySystemTypeInfo>();
            
            if (entitySystemTypeInfos.Any())
            {
                foreach (var systemTypeInfo in entitySystemTypeInfos)
                {
                    switch (systemTypeInfo.EntitySystemType)
                    {
                        case EntitySystemType.AwakeSystem:
                        {
                            awake.Add(systemTypeInfo);
                                
                            continue;
                        }
                        case EntitySystemType.UpdateSystem:
                        {
                            update.Add(systemTypeInfo);
                            continue;
                        }
                        case EntitySystemType.DestroySystem:
                        {
                            destroy.Add(systemTypeInfo);
                            continue;
                        }
                        case EntitySystemType.DeserializeSystem:
                        {
                            deserialize.Add(systemTypeInfo);
                            continue;
                        }
                        case EntitySystemType.LateUpdateSystem:
                        {
                            lateUpdate.Add(systemTypeInfo);
                            continue;
                        }
                    }
                }
            }

            // Awake
            GenerateSystemCode(builder, string.Empty, "AwakeTypeHandles", "AwakeHandles", awake);
            // Update
            GenerateSystemCode(builder, string.Empty, "UpdateTypeHandles", "UpdateHandles", update);
            // Destroy
            GenerateSystemCode(builder, string.Empty, "DestroyTypeHandles", "DestroyHandles", destroy);
            // Deserialize
            GenerateSystemCode(builder, string.Empty, "DeserializeTypeHandles", "DeserializeHandles", deserialize);
            // LateUpdate
            GenerateSystemCode(builder, "#if FANTASY_UNITY", "LateUpdateTypeHandles", "LateUpdateHandles", lateUpdate);
        }
        
        private static void GenerateSystemCode(SourceCodeBuilder builder, string defineConstants, string typeHandle, string handler, List<EntitySystemTypeInfo> systemTypeInfos)
        {
            var typeHandleBuilder = new SourceCodeBuilder(2);
            var handlerBuilder = new SourceCodeBuilder(2);

            if (!string.IsNullOrEmpty(defineConstants))
            {
                typeHandleBuilder.AppendLine(defineConstants, false);
                handlerBuilder.AppendLine(defineConstants, false);
            }
            
            typeHandleBuilder.AddXmlComment(typeHandle);
            typeHandleBuilder.BeginMethod($"public global::System.RuntimeTypeHandle[] {typeHandle}()");
            handlerBuilder.AddXmlComment(handler);
            handlerBuilder.BeginMethod($"public global::System.Action<global::Fantasy.Entitas.Entity>[] {handler}()");

            if (systemTypeInfos.Any())
            {
                typeHandleBuilder.AppendLine($"var array = new global::System.RuntimeTypeHandle[{systemTypeInfos.Count}];");
                handlerBuilder.AppendLine($"var array = new global::System.Action<global::Fantasy.Entitas.Entity>[{systemTypeInfos.Count}];");
                for (var i = 0; i < systemTypeInfos.Count; i++)
                {
                    var entitySystemTypeInfo = systemTypeInfos[i];
                    typeHandleBuilder.AppendLine($"array[{i}] = typeof({entitySystemTypeInfo.EntityTypeFullName}).TypeHandle;");
                    handlerBuilder.AppendLine($"array[{i}] = new {entitySystemTypeInfo.GlobalTypeFullName}().Invoke;");
                }
                typeHandleBuilder.AppendLine("return array;");
                handlerBuilder.AppendLine("return array;");
            }
            else
            {
                typeHandleBuilder.AppendLine("return Array.Empty<global::System.RuntimeTypeHandle>();");
                handlerBuilder.AppendLine("return Array.Empty<global::System.Action<global::Fantasy.Entitas.Entity>>();");
            }

            typeHandleBuilder.EndMethod();
            handlerBuilder.EndMethod();
            
            if (!string.IsNullOrEmpty(defineConstants))
            {
                typeHandleBuilder.AppendLine("#endif", false);
                handlerBuilder.AppendLine("#endif", false);
            }

            builder.AppendLine(typeHandleBuilder.ToString(), false);
            builder.AppendLine(handlerBuilder.ToString(), false);
        }
        
        private static bool IsSystemClass(SyntaxNode node)
        {
            if (node is not ClassDeclarationSyntax classDecl)
            {
                return false;
            }

            // 必须有基类型列表（继承抽象类）
            if (classDecl.BaseList == null || classDecl.BaseList.Types.Count == 0)
            {
                return false;
            }
            
            // 快速检查是否包含可能的 EntitySystem 基类名称
            var baseListText = classDecl.BaseList.ToString();
            return baseListText.Contains("AwakeSystem") ||
                   baseListText.Contains("UpdateSystem") ||
                   baseListText.Contains("DestroySystem") ||
                   baseListText.Contains("DeserializeSystem") ||
                   baseListText.Contains("LateUpdateSystem");
        }
        
        private enum EntitySystemType
        {
            None,
            AwakeSystem,
            UpdateSystem,
            DestroySystem,
            DeserializeSystem,
            LateUpdateSystem
        }
        
        private sealed class EntitySystemTypeInfo
        {
            public readonly EntitySystemType EntitySystemType;
            public readonly string GlobalTypeFullName;
            // public readonly string TypeFullName;
            // public readonly string TypeName;
            // public readonly long EntityTypeHashCode;  // 预计算的实体类型哈希值
            public readonly string EntityTypeFullName; // 实体类型的完整名称（用于注释）

            private EntitySystemTypeInfo(
                EntitySystemType entitySystemType,
                string globalTypeFullName,
                // string typeFullName,
                // string typeName,
                // long entityTypeHashCode,
                string entityTypeFullName)
            {
                EntitySystemType = entitySystemType;
                GlobalTypeFullName = globalTypeFullName;
                // TypeFullName = typeFullName;
                // TypeName = typeName;
                // EntityTypeHashCode = entityTypeHashCode;
                EntityTypeFullName = entityTypeFullName;
            }

            public static EntitySystemTypeInfo Create(EntitySystemType entitySystemType, INamedTypeSymbol symbol)
            {
                // 获取泛型参数 T (例如：AwakeSystem<T> 中的 T)
                var entityType = symbol.BaseType?.TypeArguments.FirstOrDefault();
                var entityTypeFullName = entityType?.GetFullName(false) ?? "Unknown";

                // // 使用与运行时相同的算法计算哈希值
                // var entityTypeHashCode = HashCodeHelper.ComputeHash64(entityTypeFullName);

                return new EntitySystemTypeInfo(
                    entitySystemType,
                    symbol.GetFullName(),
                    // symbol.GetFullName(false),
                    // symbol.Name,
                    // entityTypeHashCode,
                    entityTypeFullName);
            }
        }
    }
}
