./Exporter --ExportPlatform 3 \
--ProtoBufTemplatePath ../../../Config/Template/ProtoTemplate.txt \
--ProtoBufDirectory ../../../Config/ProtoBuf/ \
--ProtoBufServerDirectory ../../../Server/Hotfix/Generate/NetworkProtocol/ \
--ProtoBufClientDirectory ../../../Unity/Assets/Scripts/Hotfix/Generate/NetworkProtocol/ \
--ExcelProgramPath ../../../Config/Excel/ \
--ExcelVersionFile ../../../Config/Excel/Version.txt \
--ExcelServerFileDirectory ../../../Server/Hotfix/Generate/ConfigTable/Entity/ \
--ExcelClientFileDirectory ../../../Unity/Assets/Scripts/Hotfix/Generate/ConfigTable/Entity/ \
--ExcelServerBinaryDirectory ../../../Config/Binary/ \
--ExcelClientBinaryDirectory ../../../Unity/Assets/Bundles/Config/ \
--ExcelServerJsonDirectory ../../../Config/Json/Server/ \
--ExcelClientJsonDirectory ../../../Config/Json/Client/ \
--ExcelTemplatePath ../../../Config/Template/ExcelTemplate.txt \
--ServerCustomExportDirectory ../../../Server/Hotfix/Generate/CustomExport/ \
--ClientCustomExportDirectory ../../../Unity/Assets/Scripts/Hotfix/Generate/CustomExport